// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExternalRepository() {
  return window['go']['main']['App']['AddExternalRepository']();
}

export function ChooseCodeDirectory() {
  return window['go']['main']['App']['ChooseCodeDirectory']();
}

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function CloseRepository() {
  return window['go']['main']['App']['CloseRepository']();
}

export function CreateNewRepository(arg1, arg2) {
  return window['go']['main']['App']['CreateNewRepository'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSelectedRepo() {
  return window['go']['main']['App']['GetSelectedRepo']();
}

export function LogFrontendError(arg1, arg2) {
  return window['go']['main']['App']['LogFrontendError'](arg1, arg2);
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function OpenInFileExplorer(arg1) {
  return window['go']['main']['App']['OpenInFileExplorer'](arg1);
}

export function OpenRepository(arg1) {
  return window['go']['main']['App']['OpenRepository'](arg1);
}

export function OpenRepositoryFile() {
  return window['go']['main']['App']['OpenRepositoryFile']();
}

export function OpenRepositoryInEditor() {
  return window['go']['main']['App']['OpenRepositoryInEditor']();
}

export function ScanForRepositories() {
  return window['go']['main']['App']['ScanForRepositories']();
}

export function SetEditor(arg1) {
  return window['go']['main']['App']['SetEditor'](arg1);
}
