// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {reposcan} from '../models';

export function AddExternalRepository():Promise<string>;

export function ChooseCodeDirectory():Promise<string>;

export function ChooseDirectory():Promise<string>;

export function CloseRepository():Promise<void>;

export function CreateNewRepository(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<main.AppConfig>;

export function GetSelectedRepo():Promise<reposcan.DetailedRepository>;

export function LogFrontendError(arg1:string,arg2:string):Promise<void>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenInFileExplorer(arg1:string):Promise<void>;

export function OpenRepository(arg1:string):Promise<void>;

export function OpenRepositoryFile():Promise<void>;

export function OpenRepositoryInEditor():Promise<void>;

export function ScanForRepositories():Promise<Array<reposcan.Repository>>;

export function SetEditor(arg1:string):Promise<void>;
